"""
auto_login.py
SEMI-automates the daily Upstox access-token refresh via Selenium: fills
your registered mobile number and clicks "Get OTP" automatically, then
PAUSES and asks you to type in the SMS OTP Upstox just texted you (that
code can't be automated -- see the module-level note below). If a TOTP or
PIN field appears after the OTP step, it's filled in automatically from
your stored secret. Once past login, captures the OAuth redirect's auth
code and exchanges it for a fresh access token -- the same call
1_generate_token.py makes interactively.

*** WHY THIS ISN'T FULLY AUTOMATIC ***
Upstox's actual OAuth login page (verified 2026-07-20 against the live
page, not guessed) is "Login with mobile number" -- it sends a fresh SMS
OTP to your registered phone on every login. That code is generated by
Upstox server-side per attempt; it is NOT derivable from any stored secret
(unlike a TOTP code, which pyotp generates locally from upstox_totp_secret
without contacting anyone). Nothing this script does can know that code in
advance. Genuinely automating past this would require reading the SMS off
your phone via a separate always-on integration (e.g. a phone-side
forwarding app relaying the code to this script) -- not built here.

*** RUN THIS YOURSELF, NEVER LET AN AGENT RUN IT ***
This script enters your PIN/TOTP-derived code to authenticate as you --
that's true regardless of who's asking it to run. You run it, not an
assistant, even if the assistant wrote it.

Needs in .streamlit/secrets.toml (gitignored, local only):
  upstox_mobile_number       -- your Upstox-registered 10-digit mobile number
                                 (NOT your Client Code/UCC -- the login page
                                 asks for the phone number, confirmed live)
  upstox_pin                 -- your trading PIN (used only if a PIN field
                                 appears after the OTP step -- may not apply)
  upstox_totp_secret         -- base32 TOTP secret from 2FA setup (NOT the
                                 6-digit code), used only if a TOTP field
                                 appears after the OTP step
  upstox_app_client_id / upstox_app_client_secret -- your developer app's
                                 OAuth credentials (same as UPSTOX_CLIENT_ID/
                                 UPSTOX_CLIENT_SECRET in 1_generate_token.py;
                                 falls back to those env vars if unset here)

*** SECURITY NOTE ***
A PIN + TOTP secret is enough to fully log into your real Upstox account --
this is meaningfully more sensitive than the Telegram bot token or the
Upstox ACCESS token already stored in this file (an access token expires
in hours and only allows API calls; your PIN+TOTP secret allows logging in
as you, indefinitely, anywhere). secrets.toml is gitignored but NOT
encrypted at rest -- anyone with access to this machine/file has full
account access. Only proceed if you're comfortable with that tradeoff on
this specific machine.
"""
import os
import re

import pyotp
import requests
from selenium import webdriver
from selenium.webdriver.chrome.service import Service as ChromeService
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

REDIRECT_URI = "https://127.0.0.1"
LOGIN_TIMEOUT_SECONDS = 30
BASE_DIR = os.path.dirname(os.path.abspath(__file__))

# Selenium Manager (the bundled driver auto-downloader) has no win32/arm64
# mapping for either Chrome or Edge -- fails outright on Windows-on-ARM
# machines with "Unsupported platform/architecture combination", and
# Microsoft's own EdgeDriver hosting (msedgedriver.azurewebsites.net) turned
# out to be retired/access-blocked when checked 2026-07-20. Worked around by
# manually downloading a win64 chromedriver build (Chrome for Testing) into
# drivers/ -- win64 drivers run fine on ARM64 Windows via the OS's built-in
# x64 emulation, since the driver only talks to Chrome over a local network
# port (DevTools Protocol), not native code, so the architecture mismatch
# between driver and browser doesn't matter. If Chrome auto-updates past
# what this driver supports, re-run the download step in AUTO_LOGIN_SETUP.md.
CHROMEDRIVER_PATH = os.path.join(BASE_DIR, "drivers", "chromedriver-win64", "chromedriver.exe")


def _get_secret(key, env_var=None):
    try:
        import streamlit as st
        value = st.secrets.get(key)
        if value:
            return value
    except Exception:
        pass
    return os.environ.get(env_var) if env_var else None


def _find_first(driver, selectors, timeout=LOGIN_TIMEOUT_SECONDS):
    """Tries each (By, value) selector in order, returns the first element
    that appears within `timeout` seconds total (not per-selector) -- used
    where the exact field ID for a page we haven't fully mapped yet is a
    best guess among a few plausible candidates, e.g. the OTP field, or
    whatever optional step follows it."""
    wait = WebDriverWait(driver, timeout)
    last_exc = None
    for by, value in selectors:
        try:
            return wait.until(EC.presence_of_element_located((by, value)), message="")
        except Exception as e:
            last_exc = e
            continue
    raise last_exc


def _get_access_token_via_browser(app_client_id, app_client_secret, mobile_number, pin, totp_secret):
    auth_url = (
        f"https://api.upstox.com/v2/login/authorization/dialog"
        f"?response_type=code&client_id={app_client_id}&redirect_uri={REDIRECT_URI}"
    )

    if not os.path.exists(CHROMEDRIVER_PATH):
        raise RuntimeError(
            f"chromedriver.exe not found at {CHROMEDRIVER_PATH} -- see AUTO_LOGIN_SETUP.md's "
            f"'Windows-on-ARM' section to download it."
        )

    options = webdriver.ChromeOptions()
    # NOT headless: you need to see the browser is genuinely at the OTP
    # step before typing the SMS code in below -- headless would leave you
    # guessing whether it's actually waiting there yet.
    options.add_argument("--disable-gpu")
    options.add_argument("--no-sandbox")
    options.add_argument("--window-size=1280,900")
    service = ChromeService(executable_path=CHROMEDRIVER_PATH)
    driver = webdriver.Chrome(service=service, options=options)

    debug_dir = os.path.join(BASE_DIR, "drivers", "debug")
    os.makedirs(debug_dir, exist_ok=True)

    def _dump_debug(step_name):
        """Saves a screenshot + full page HTML so a failed selector can be
        diagnosed from these files instead of live DOM inspection -- drivers/
        is gitignored. Screenshots visually mask password-type fields, but
        page_source does NOT (the raw value= attribute is still in the DOM
        even for type="password" inputs), so every password/PIN/OTP-shaped
        input is blanked via JS before the HTML is captured."""
        try:
            driver.execute_script("""
                document.querySelectorAll(
                    'input[type="password"], input[id="pinCode"], input[id="otpNum"], '
                    + 'input[id="otp"], input[maxlength="6"]'
                ).forEach(el => el.value = '[REDACTED]');
            """)
        except Exception:
            pass
        png_path = os.path.join(debug_dir, f"{step_name}.png")
        html_path = os.path.join(debug_dir, f"{step_name}.html")
        try:
            driver.save_screenshot(png_path)
            with open(html_path, "w", encoding="utf-8") as f:
                f.write(driver.page_source)
        except Exception:
            png_path = html_path = "(failed to save)"
        return png_path, html_path

    try:
        driver.get(auth_url)
        wait = WebDriverWait(driver, LOGIN_TIMEOUT_SECONDS)

        # Step 1: mobile number (confirmed live 2026-07-20 -- digits-only
        # field, id="mobileNum", 10 digits required to enable "Get OTP")
        try:
            mobile_field = wait.until(EC.presence_of_element_located((By.ID, "mobileNum")))
        except Exception as e:
            png, html = _dump_debug("step1_mobile_number")
            raise RuntimeError(
                f"Could not find the mobile number input field (tried id='mobileNum'). "
                f"Saved a screenshot/HTML dump:\n  {png}\n  {html}"
            ) from e
        mobile_field.clear()
        mobile_field.send_keys(re.sub(r"\D", "", mobile_number))  # digits only, matches the field's own filtering
        driver.find_element(By.ID, "getOtp").click()

        # Step 2: SMS OTP -- CANNOT be automated (see module docstring).
        # Selector is a best guess among a few plausible IDs; if none
        # match within the timeout, dump debug and let you report the
        # real one back instead of guessing further blind.
        try:
            otp_field = _find_first(driver, [
                (By.ID, "otpNum"), (By.ID, "otp"), (By.NAME, "otp"),
                (By.CSS_SELECTOR, "input[maxlength='6']"),
            ])
        except Exception as e:
            png, html = _dump_debug("step2_otp_field_not_found")
            raise RuntimeError(
                f"Could not find the OTP input field after requesting the SMS OTP. "
                f"Saved a screenshot/HTML dump:\n  {png}\n  {html}"
            ) from e

        print("\n*** Check your phone -- Upstox just sent you an SMS OTP. ***")
        sms_otp = input("Enter the OTP here: ").strip()
        otp_field.send_keys(sms_otp)
        try:
            driver.find_element(By.ID, "otpContinueBtn").click()
        except Exception:
            # Some flows auto-submit once all OTP digits are entered --
            # only click a continue button if one actually exists.
            pass

        # Step 3 (OPTIONAL): PIN and/or TOTP, IF Upstox asks for a second
        # factor after the SMS OTP -- unconfirmed whether this flow has one
        # at all. If neither field shows up within the timeout, assume the
        # SMS OTP alone was sufficient and move on to the redirect wait.
        try:
            second_factor_field = _find_first(
                driver,
                [(By.ID, "pinCode"), (By.ID, "otpNum"), (By.CSS_SELECTOR, "input[type='password']")],
                timeout=10,
            )
            field_id = second_factor_field.get_attribute("id") or ""
            if "pin" in field_id.lower():
                second_factor_field.send_keys(pin)
            else:
                second_factor_field.send_keys(pyotp.TOTP(totp_secret).now())
            for btn_id in ("pinContinueBtn", "continueBtn"):
                try:
                    driver.find_element(By.ID, btn_id).click()
                    break
                except Exception:
                    continue
        except Exception:
            pass  # no second factor shown -- SMS OTP alone must have been enough

        # Wait for the redirect back to REDIRECT_URI with ?code=...
        try:
            wait.until(lambda d: d.current_url.startswith(REDIRECT_URI))
        except Exception as e:
            png, html = _dump_debug("step4_redirect")
            raise RuntimeError(
                f"Login did not redirect to {REDIRECT_URI} within {LOGIN_TIMEOUT_SECONDS}s -- "
                f"still on: {driver.current_url}. Likely a wrong OTP/PIN/TOTP, an unexpected "
                f"extra step (e.g. a consent screen), or a login-page change. Saved a dump:\n"
                f"  {png}\n  {html}"
            ) from e
        redirected_url = driver.current_url
    finally:
        driver.quit()

    if "code=" not in redirected_url:
        raise RuntimeError(f"Redirected, but no auth code in the URL -- got: {redirected_url}")
    auth_code = redirected_url.split("code=")[1].split("&")[0]

    token_url = "https://api.upstox.com/v2/login/authorization/token"
    payload = {
        "code": auth_code,
        "client_id": app_client_id,
        "client_secret": app_client_secret,
        "redirect_uri": REDIRECT_URI,
        "grant_type": "authorization_code",
    }
    headers = {"accept": "application/json", "Content-Type": "application/x-www-form-urlencoded"}
    resp = requests.post(token_url, data=payload, headers=headers, timeout=15)
    resp.raise_for_status()
    data = resp.json()
    access_token = data.get("access_token")
    if not access_token:
        raise RuntimeError(f"No access_token in the token-exchange response: {data}")
    return access_token


def _write_token(access_token):
    """Writes to BOTH upstox_token.txt and secrets.toml so
    option_selector.get_access_token() picks it up regardless of which
    source it prefers (secrets.toml first, then the local file)."""
    token_file = os.path.join(BASE_DIR, "upstox_token.txt")
    with open(token_file, "w") as f:
        f.write(access_token)

    secrets_path = os.path.join(BASE_DIR, ".streamlit", "secrets.toml")
    if os.path.exists(secrets_path):
        with open(secrets_path) as f:
            lines = f.readlines()
        found = False
        for i, line in enumerate(lines):
            if line.strip().startswith("upstox_token"):
                lines[i] = f'upstox_token = "{access_token}"\n'
                found = True
                break
        if not found:
            lines.append(f'\nupstox_token = "{access_token}"\n')
        with open(secrets_path, "w") as f:
            f.writelines(lines)


def refresh_token():
    """Returns the new access token, or raises with a specific reason.
    Semi-automatic: prompts for the SMS OTP on stdin partway through (see
    module docstring for why that step can't be automated)."""
    mobile_number = _get_secret("upstox_mobile_number")
    pin = _get_secret("upstox_pin")
    totp_secret = _get_secret("upstox_totp_secret")
    app_client_id = _get_secret("upstox_app_client_id", "UPSTOX_CLIENT_ID")
    app_client_secret = _get_secret("upstox_app_client_secret", "UPSTOX_CLIENT_SECRET")

    missing = [name for name, val in [
        ("upstox_mobile_number", mobile_number),
        ("upstox_app_client_id / UPSTOX_CLIENT_ID", app_client_id),
        ("upstox_app_client_secret / UPSTOX_CLIENT_SECRET", app_client_secret),
    ] if not val]
    if missing:
        raise RuntimeError(
            f"Missing credentials for auto-login: {', '.join(missing)}. "
            f"Add them to .streamlit/secrets.toml -- see auto_login.py's module docstring."
        )
    # pin/totp_secret are optional -- only used IF a second-factor field
    # actually appears after the SMS OTP; not yet confirmed whether it does.

    access_token = _get_access_token_via_browser(
        app_client_id, app_client_secret, mobile_number, pin, totp_secret
    )
    _write_token(access_token)
    return access_token


if __name__ == "__main__":
    token = refresh_token()
    print(f"Access token refreshed successfully. First 20 chars: {token[:20]}...")
